spring:
  datasource:
    username: postgres
    password: 1111
    url: jdbc:postgresql://localhost:5432/url_shortener
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090